version: "3.9"

services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: openjobs
      MYSQL_ROOT_PASSWORD: password
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
networks:
  openjobs:
    driver: bridge
