spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    default-schema: openjobs
    locations:
      - classpath:/db/changelog/master
jwt:
  secret: 84d35817-7f97-459f-ab4c-bd44161a5546
  expiresIn: 360000