spring:
  datasource:
    url: jdbc:mysql://localhost:3307/openjobs
    username: root
    password: password
  jpa:
#    properties:
#      hibernate:
#        default_schema: openjobs
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: openjobs