spring:
  datasource:
    url: jdbc:mysql://localhost:3307/openjobs
    username: root
    password: password
  flyway:
    locations:
      - classpath:/db/changelog/master
      - classpath:/db/changelog/local