spring:
  datasource:
    url: jdbc:mysql://localhost:3307/openjobs
    username: root
    password: password
  flyway:
    locations:
      - classpath:/db/changelog/master
      - classpath:/db/changelog/local
  mail:
    host: localhost
    port: 1025
    username: root
    password: password
    properties.mail.smtp:
      auth: true
      starttls.enable: true